// File generated by hgctl. Modify as required.
// See: https://higress.io/zh-cn/docs/user/wasm-go#2-%E7%BC%96%E5%86%99-maingo-%E6%96%87%E4%BB%B6

package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strconv"
	"strings"

	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-cache/dashscope"
	"github.com/alibaba/higress/plugins/wasm-go/extensions/ai-cache/promptTemplate"
	"github.com/alibaba/higress/plugins/wasm-go/pkg/wrapper"
	"github.com/alibaba/tair-go/tair"
	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm"
	"github.com/higress-group/proxy-wasm-go-sdk/proxywasm/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/resp"
)

const (
	CacheKeyContextKey       = "cacheKey"
	CacheContentContextKey   = "cacheContent"
	PartialMessageContextKey = "partialMessage"
	ToolCallsContextKey      = "toolCalls"
	StreamContextKey         = "stream"
	DefaultCacheKeyPrefix    = "higress-ai-cache:"
)

func main() {
	wrapper.SetCtx(
		"ai-cache",
		wrapper.ParseConfigBy(parseConfig),
		wrapper.ProcessRequestHeadersBy(onHttpRequestHeaders),
		wrapper.ProcessRequestBodyBy(onHttpRequestBody),
		wrapper.ProcessResponseHeadersBy(onHttpResponseHeaders),
		//wrapper.ProcessStreamingResponseBodyBy(onHttpResponseBody),
		wrapper.ProcessResponseBodyBy(onHttpResponseBody),
	)
}

// @Name ai-cache
// @Category protocol
// @Phase AUTHN
// @Priority 10
// @Title zh-CN AI Cache
// @Description zh-CN 大模型结果缓存
// @IconUrl
// @Version 0.1.0
//
// @Contact.name johnlanni
// @Contact.url
// @Contact.email
//
// @Example
// redis:
//   serviceName: my-redis.dns
//   timeout: 2000
// cacheKeyFrom:
//   requestBody: "messages.@reverse.0.content"
// cacheValueFrom:
//   responseBody: "choices.0.message.content"
// cacheStreamValueFrom:
//   responseBody: "choices.0.delta.content"
// returnResponseTemplate: |
//   {"id":"from-cache","choices":[{"index":0,"message":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
// returnStreamResponseTemplate: |
//   data:{"id":"from-cache","choices":[{"index":0,"delta":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
//
//   data:[DONE]
//
// @End

type RedisInfo struct {
	// @Title zh-CN redis 服务名称
	// @Description zh-CN 带服务类型的完整 FQDN 名称，例如 my-redis.dns、redis.my-ns.svc.cluster.local
	ServiceName string `required:"true" yaml:"serviceName" json:"serviceName"`
	// @Title zh-CN redis 服务端口
	// @Description zh-CN 默认值为6379
	ServicePort int `required:"false" yaml:"servicePort" json:"servicePort"`
	// @Title zh-CN 用户名
	// @Description zh-CN 登陆 redis 的用户名，非必填
	Username string `required:"false" yaml:"username" json:"username"`
	// @Title zh-CN 密码
	// @Description zh-CN 登陆 redis 的密码，非必填，可以只填密码
	Password string `required:"false" yaml:"password" json:"password"`
	// @Title zh-CN 索引名称
	// @Description zh-CN 索引名称
	IndexName string `required:"true" yaml:"indexName" json:"indexName"`
	// @Title zh-CN 请求超时
	// @Description zh-CN 请求 redis 的超时时间，单位为毫秒。默认值是1000，即1秒
	Timeout int `required:"false" yaml:"timeout" json:"timeout"`
}

type DashScopeInfo struct {
	// @Title zh-CN tair 服务名称
	// @Description zh-CN 带服务类型的完整 FQDN 名称，例如 my-redis.dns、redis.my-ns.svc.cluster.local
	ServiceName string `required:"true" yaml:"serviceName" json:"serviceName"`
	// @Title zh-CN tair 服务端口
	// @Description zh-CN 默认值为6379
	ServicePort int64 `required:"true" yaml:"servicePort" json:"servicePort"`
	// @Title zh-CN tair 服务名称
	// @Description zh-CN 带服务类型的完整 FQDN 名称，例如 my-redis.dns、redis.my-ns.svc.cluster.local
	Domin string `required:"true" yaml:"domin" json:"domin"`
	// @Title zh-CN 向量检索服务的key
	// @Description zh-CN 向量检索服务的key
	APIKey string `required:"true" yaml:"apiKey" json:"apiKey"`
}

type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type Request struct {
	Model            string    `json:"model"`
	Messages         []Message `json:"messages"`
	FrequencyPenalty float64   `json:"frequency_penalty"`
	PresencePenalty  float64   `json:"presence_penalty"`
	Stream           bool      `json:"stream"`
	Temperature      float64   `json:"temperature"`
	Topp             int32     `json:"top_p"`
}

type Choice struct {
	Index        int     `json:"index"`
	Message      Message `json:"message"`
	FinishReason string  `json:"finish_reason"`
}

type Usage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

type Response struct {
	ID      string   `json:"id"`
	Choices []Choice `json:"choices"`
	Created int64    `json:"created"`
	Model   string   `json:"model"`
	Object  string   `json:"object"`
	Usage   Usage    `json:"usage"`
}

type OutPutFormat struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type KVExtractor struct {
	// @Title zh-CN 从请求 Body 中基于 [GJSON PATH](https://github.com/tidwall/gjson/blob/master/SYNTAX.md) 语法提取字符串
	RequestBody string `required:"false" yaml:"requestBody" json:"requestBody"`
	// @Title zh-CN 从响应 Body 中基于 [GJSON PATH](https://github.com/tidwall/gjson/blob/master/SYNTAX.md) 语法提取字符串
	ResponseBody string `required:"false" yaml:"responseBody" json:"responseBody"`
}

type PluginConfig struct {
	// @Title zh-CN Redis 地址信息
	// @Description zh-CN 用于存储缓存结果的 Redis 地址
	RedisInfo RedisInfo `required:"true" yaml:"redis" json:"redis"`
	// @Title zh-CN dashscope信息
	// @Description zh-CN 用于存储dashscope使用信息
	DashScopeInfo DashScopeInfo `required:"true" yaml:"dashscope" json:"dashscope"`
	// @Title zh-CN 缓存 key 的来源
	// @Description zh-CN 往 redis 里存时，使用的 key 的提取方式
	CacheKeyFrom KVExtractor `required:"true" yaml:"cacheKeyFrom" json:"cacheKeyFrom"`
	// @Title zh-CN 缓存 value 的来源
	// @Description zh-CN 往 redis 里存时，使用的 value 的提取方式
	CacheValueFrom KVExtractor `required:"true" yaml:"cacheValueFrom" json:"cacheValueFrom"`
	// @Title zh-CN 流式响应下，缓存 value 的来源
	// @Description zh-CN 往 redis 里存时，使用的 value 的提取方式
	CacheStreamValueFrom KVExtractor `required:"true" yaml:"cacheStreamValueFrom" json:"cacheStreamValueFrom"`
	// @Title zh-CN 返回 HTTP 响应的模版
	// @Description zh-CN 用 %s 标记需要被 cache value 替换的部分
	ReturnResponseTemplate string `required:"true" yaml:"returnResponseTemplate" json:"returnResponseTemplate"`
	// @Title zh-CN 返回流式 HTTP 响应的模版
	// @Description zh-CN 用 %s 标记需要被 cache value 替换的部分
	ReturnStreamResponseTemplate string `required:"true" yaml:"returnStreamResponseTemplate" json:"returnStreamResponseTemplate"`
	// @Title zh-CN 缓存的过期时间
	// @Description zh-CN 单位是秒，默认值为0，即永不过期
	CacheTTL int `required:"false" yaml:"cacheTTL" json:"cacheTTL"`
	// @Title zh-CN Redis缓存Key的前缀
	// @Description zh-CN 默认值是"higress-ai-cache:"
	CacheKeyPrefix  string              `required:"false" yaml:"cacheKeyPrefix" json:"cacheKeyPrefix"`
	redisClient     wrapper.RedisClient `yaml:"-" json:"-"`
	DashScopeClient wrapper.HttpClient  `yaml:"-" json:"-"`
}

func parseConfig(json gjson.Result, c *PluginConfig, log wrapper.Log) error {
	c.RedisInfo.ServiceName = json.Get("redis.serviceName").String()
	if c.RedisInfo.ServiceName == "" {
		return errors.New("redis service name must not by empty")
	}
	c.RedisInfo.ServicePort = int(json.Get("redis.servicePort").Int())
	if c.RedisInfo.ServicePort == 0 {
		if strings.HasSuffix(c.RedisInfo.ServiceName, ".static") {
			// use default logic port which is 80 for static service
			c.RedisInfo.ServicePort = 80
		} else {
			c.RedisInfo.ServicePort = 6379
		}
	}
	c.RedisInfo.Username = json.Get("redis.username").String()
	c.RedisInfo.Password = json.Get("redis.password").String()
	c.RedisInfo.IndexName = json.Get("redis.indexName").String()
	c.RedisInfo.Timeout = int(json.Get("redis.timeout").Int())
	if c.RedisInfo.Timeout == 0 {
		c.RedisInfo.Timeout = 1000
	}
	c.CacheKeyFrom.RequestBody = json.Get("cacheKeyFrom.requestBody").String()
	if c.CacheKeyFrom.RequestBody == "" {
		c.CacheKeyFrom.RequestBody = "messages.@reverse.0.content"
	}
	c.CacheValueFrom.ResponseBody = json.Get("cacheValueFrom.responseBody").String()
	if c.CacheValueFrom.ResponseBody == "" {
		c.CacheValueFrom.ResponseBody = "choices.0.message.content"
	}
	c.CacheStreamValueFrom.ResponseBody = json.Get("cacheStreamValueFrom.responseBody").String()
	if c.CacheStreamValueFrom.ResponseBody == "" {
		c.CacheStreamValueFrom.ResponseBody = "choices.0.delta.content"
	}
	c.ReturnResponseTemplate = json.Get("returnResponseTemplate").String()
	if c.ReturnResponseTemplate == "" {
		c.ReturnResponseTemplate = `{"id":"from-cache","choices":[{"index":0,"message":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}`
	}
	c.ReturnStreamResponseTemplate = json.Get("returnStreamResponseTemplate").String()
	if c.ReturnStreamResponseTemplate == "" {
		c.ReturnStreamResponseTemplate = `data:{"id":"from-cache","choices":[{"index":0,"delta":{"role":"assistant","content":"%s"},"finish_reason":"stop"}],"model":"gpt-4o","object":"chat.completion","usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}` + "\n\ndata:[DONE]\n\n"
	}
	c.CacheKeyPrefix = json.Get("cacheKeyPrefix").String()
	if c.CacheKeyPrefix == "" {
		c.CacheKeyPrefix = DefaultCacheKeyPrefix
	}
	c.redisClient = wrapper.NewRedisClusterClient(wrapper.FQDNCluster{
		FQDN: c.RedisInfo.ServiceName,
		Port: int64(c.RedisInfo.ServicePort),
	})

	c.DashScopeInfo.APIKey = json.Get("dashscope.apiKey").String()
	c.DashScopeInfo.ServiceName = json.Get("dashscope.serviceName").String()
	c.DashScopeInfo.ServicePort = json.Get("dashscope.servicePort").Int()
	c.DashScopeInfo.Domin = json.Get("dashscope.domain").String()

	c.DashScopeClient = wrapper.NewClusterClient(wrapper.DnsCluster{
		ServiceName: c.DashScopeInfo.ServiceName,
		Port:        c.DashScopeInfo.ServicePort,
		Domain:      c.DashScopeInfo.Domin,
	})

	return c.redisClient.Init(c.RedisInfo.Username, c.RedisInfo.Password, int64(c.RedisInfo.Timeout))
}

func onHttpRequestHeaders(ctx wrapper.HttpContext, config PluginConfig, log wrapper.Log) types.Action {
	log.Info("onHttpRequestHeaders start")
	defer log.Info("onHttpRequestHeaders end")
	contentType, _ := proxywasm.GetHttpRequestHeader("content-type")
	// The request does not have a body.
	if contentType == "" {
		return types.ActionContinue
	}
	if !strings.Contains(contentType, "application/json") {
		log.Warnf("content is not json, can't process:%s", contentType)
		ctx.DontReadRequestBody()
		return types.ActionContinue
	}
	proxywasm.RemoveHttpRequestHeader("Accept-Encoding")
	// The request has a body and requires delaying the header transmission until a cache miss occurs,
	// at which point the header should be sent.
	return types.HeaderStopIteration
}

func TrimQuote(source string) string {
	return strings.Trim(source, `"`)
}

func FloatSliceToString(slice []float32) string {
	strs := make([]string, len(slice))
	for i, v := range slice {
		strs[i] = strconv.FormatFloat(float64(v), 'f', -1, 32)
	}
	return "[" + strings.Join(strs, ",") + "]"
}

func SearchVector(ctx wrapper.HttpContext, config PluginConfig, key string, rawRequest Request, stream bool, log wrapper.Log) {
	log.Info("[onHttpRequestBody] 开始转向量了")
	// text to vector
	requestEmbedding := dashscope.Request{
		Model: "text-embedding-v2",
		Input: dashscope.Input{
			Texts: []string{key},
		},
		Parameter: dashscope.Parameter{
			TextType: "query",
		},
	}

	headers := [][2]string{{"Content-Type", "application/json"}, {"Authorization", "Bearer " + config.DashScopeInfo.APIKey}}
	reqEmbeddingSerialized, _ := json.Marshal(requestEmbedding)
	err := config.DashScopeClient.Post(
		"/api/v1/services/embeddings/text-embedding/text-embedding",
		headers,
		reqEmbeddingSerialized,
		func(statusCode int, responseHeaders http.Header, responseBody []byte) {
			//vector search
			var responseEmbedding dashscope.Response
			_ = json.Unmarshal(responseBody, &responseEmbedding)
			vector := responseEmbedding.Output.Embeddings[0].Embedding
			sVector := FloatSliceToString(vector)

			log.Infof("[onHttpRequestBody] svector: ", sVector)

			err := config.redisClient.TvsKnnSearch(config.RedisInfo.IndexName, 1, sVector, tair.TvsKnnSearchArgs{}.New().MaxDist(0.25), func(response resp.Value) {
				if err := response.Error(); err != nil {
					log.Errorf("[onHttpRequestBody] tair search vector:%s failed, err:%v", key, err)
					proxywasm.ResumeHttpRequest()
					return
				}

				log.Infof("[onHttpRequestBody] TvsKnnSearch: %s", response.String())

				if response.String() == "[]" { // cache miss
					log.Infof("[onHttpRequestBody] cache miss not find key:%s", key)
					//add system role message
					var systemMessage Message
					systemMessage.Role = "system"
					systemMessage.Content = promptTemplate.Instruction + promptTemplate.OutputFormat + promptTemplate.Order + promptTemplate.Example

					//从redis中获取上一个问题
					config.redisClient.Get("lastquestion", func(response resp.Value) {
						if err := response.Error(); err != nil {
							log.Errorf("[onHttpRequestBody] redis get key:%s failed, err:%v", "lastquestion", err)
						}
						if response.IsNull() {
							log.Infof("[onHttpRequestBody] cache miss, key:%s", "lastquestion")

							newMessages := []Message{systemMessage}
							newMessages = append(newMessages, rawRequest.Messages...)
							rawRequest.Messages = newMessages

							//replace old message and resume request qwen
							newbody, err := json.Marshal(rawRequest)
							if err != nil {
								proxywasm.ResumeHttpRequest()
								return
							} else {
								log.Infof("[onHttpRequestBody] newRequestBody: ", string(newbody))
								err := proxywasm.ReplaceHttpRequestBody(newbody)
								if err != nil {
									log.Info("替换失败")
									proxywasm.SendHttpResponse(200, [][2]string{{"content-type", "application/json; charset=utf-8"}}, []byte(fmt.Sprintf(config.ReturnResponseTemplate, "替换失败"+err.Error())), -1)
								}
								log.Info("[onHttpRequestBody] request替换成功")
								proxywasm.ResumeHttpRequest()
							}
						}

						log.Debugf("[onHttpRequestBody] cache hit, key:%s", "lastquestion")
						lastquestion := response.String()
						config.redisClient.Get("lastanswer", func(response resp.Value) {
							if err := response.Error(); err != nil {
								log.Errorf("[onHttpRequestBody] redis get key:%s failed, err:%v", "lastanswer", err)
							}

							if response.IsNull() {
								log.Infof("[onHttpRequestBody] cache miss, key:%s", "lastanswer")
							}

							log.Debugf("[onHttpRequestBody] cache hit, key:%s", "lastanswer")

							historyPromptTemplate := "history: human:%s AI:%s question:%s"

							prompt := fmt.Sprintf(historyPromptTemplate, lastquestion, response.String(), key)
							rawRequest.Messages[len(rawRequest.Messages)-1].Content = prompt

							newMessages := []Message{systemMessage}
							newMessages = append(newMessages, rawRequest.Messages...)
							rawRequest.Messages = newMessages

							//replace old message and resume request qwen
							newbody, err := json.Marshal(rawRequest)
							if err != nil {
								proxywasm.ResumeHttpRequest()
								return
							} else {
								log.Infof("[onHttpRequestBody] newRequestBody: ", string(newbody))
								err := proxywasm.ReplaceHttpRequestBody(newbody)
								if err != nil {
									log.Info("替换失败")
									proxywasm.SendHttpResponse(200, [][2]string{{"content-type", "application/json; charset=utf-8"}}, []byte(fmt.Sprintf(config.ReturnResponseTemplate, "替换失败"+err.Error())), -1)
								}
								log.Info("[onHttpRequestBody] request替换成功")
								proxywasm.ResumeHttpRequest()
							}
						})
					})
				} else {
					//cache hit
					knnresp := response.Array()
					firstKey := knnresp[0]

					log.Infof("[onHttpRequestBody] cache hit, key:%s", firstKey.String())
					config.redisClient.TvsHGetAll(config.RedisInfo.IndexName, firstKey.String(), func(response resp.Value) {
						ctx.SetContext(CacheKeyContextKey, nil)
						log.Infof("[onHttpRequestBody] TvsHGetAll: %s", response.String())
						getallresp := response.Array()
						answerk := -1
						for k, v := range getallresp {
							if v.String() == "answer" {
								answerk = k
								break
							}
						}

						log.Infof("[onHttpRequestBody] answerk: %d, getallresp[answerk+1]:= %s", answerk, getallresp[answerk+1])

						if !stream {
							proxywasm.SendHttpResponse(200, [][2]string{{"content-type", "application/json; charset=utf-8"}}, []byte(fmt.Sprintf(config.ReturnResponseTemplate, getallresp[answerk+1])), -1)
						} else {
							proxywasm.SendHttpResponse(200, [][2]string{{"content-type", "text/event-stream; charset=utf-8"}}, []byte(fmt.Sprintf(config.ReturnStreamResponseTemplate, getallresp[answerk+1])), -1)
						}
					})
				}
			})
			if err != nil {
				log.Error("[onHttpRequestBody] key search failed")
				proxywasm.ResumeHttpRequest()
				return
			}
			//	proxywasm.ResumeHttpRequest()
		}, 50000)
	if err != nil {
		log.Infof("[onHttpRequestBody] 向量转错了：", err.Error())
	}
}

func onHttpRequestBody(ctx wrapper.HttpContext, config PluginConfig, body []byte, log wrapper.Log) types.Action {
	log.Info("onHttpRequestBody start")
	defer log.Info("onHttpRequestBody end")

	log.Infof("[onHttpRequestBody] body to string: ", string(body))

	var rawRequest Request
	err := json.Unmarshal(body, &rawRequest)
	if err != nil {
		log.Infof("[onHttpRequestBody] body json umarshal err: ", err.Error())
		return types.ActionContinue
	}

	stream := false

	if rawRequest.Stream {
		stream = true
		ctx.SetContext(StreamContextKey, struct{}{})
	} else if ctx.GetContext(StreamContextKey) != nil {

		stream = true
	}

	var key string
	messageLength := len(rawRequest.Messages)
	log.Infof("[onHttpRequestBody] messageLength: ", messageLength)
	if messageLength > 0 {
		key = rawRequest.Messages[messageLength-1].Content
		log.Infof("[onHttpRequestBody] key: ", key)
	} else {
		return types.ActionContinue
	}

	if key == "" {
		log.Debug("parse key from request body failed")
		return types.ActionContinue
	}
	log.Infof("CacheKeyContextKey: ", CacheKeyContextKey)
	ctx.SetContext(CacheKeyContextKey, key)
	log.Infof("[onHttpRequestBody] IndexName: ", config.RedisInfo.IndexName)
	//get tairvector index

	err = config.redisClient.TvsGetIndex(config.RedisInfo.IndexName, func(response resp.Value) {
		log.Infof("[onHttpRequestBody] TvsGetIndex: ", response.String())
		if err := response.Error(); err != nil {
			log.Errorf("tair get index:%s failed, err:%v", key, err)
			proxywasm.ResumeHttpRequest()
		}

		if response.String() == "[]" { //not find index
			log.Infof("[onHttpRequestBody] not find index:%s", config.RedisInfo.IndexName)
			//create index
			config.redisClient.TvsCreateIndex(config.RedisInfo.IndexName, 1536, "HNSW", "COSINE", nil, func(response resp.Value) {
				SearchVector(ctx, config, key, rawRequest, stream, log)
			})
		} else { //find index
			log.Infof("[onHttpRequestBody] find index:%s", config.RedisInfo.IndexName)
			SearchVector(ctx, config, key, rawRequest, stream, log)
		}
	})

	if err != nil {
		log.Error("get index failed")
		return types.ActionContinue
	}

	return types.ActionPause
}

/*func processSSEMessage(ctx wrapper.HttpContext, config PluginConfig, sseMessage string, log wrapper.Log) string {
	subMessages := strings.Split(sseMessage, "\n")
	var message string
	for _, msg := range subMessages {
		if strings.HasPrefix(msg, "data:") {
			message = msg
			break
		}
	}
	if len(message) < 6 {
		log.Errorf("invalid message:%s", message)
		return ""
	}
	// skip the prefix "data:"
	bodyJson := message[5:]
	if gjson.Get(bodyJson, config.CacheStreamValueFrom.ResponseBody).Exists() {
		tempContentI := ctx.GetContext(CacheContentContextKey)
		if tempContentI == nil {
			content := TrimQuote(gjson.Get(bodyJson, config.CacheStreamValueFrom.ResponseBody).Raw)
			ctx.SetContext(CacheContentContextKey, content)
			return content
		}
		append := TrimQuote(gjson.Get(bodyJson, config.CacheStreamValueFrom.ResponseBody).Raw)
		content := tempContentI.(string) + append
		ctx.SetContext(CacheContentContextKey, content)
		return content
	} else if gjson.Get(bodyJson, "choices.0.delta.content.tool_calls").Exists() {
		// TODO: compatible with other providers
		ctx.SetContext(ToolCallsContextKey, struct{}{})
		return ""
	}
	log.Debugf("unknown message:%s", bodyJson)
	return ""
}*/

func onHttpResponseHeaders(ctx wrapper.HttpContext, config PluginConfig, log wrapper.Log) types.Action {
	log.Info("onHttpResponseHeaders start")
	defer log.Info("onHttpResponseHeaders end")
	contentType, _ := proxywasm.GetHttpResponseHeader("content-type")
	if strings.Contains(contentType, "text/event-stream") {
		ctx.SetContext(StreamContextKey, struct{}{})
	}
	return types.ActionContinue
}

func cleanMarkdown(data []byte) []byte {
	// 定义正则表达式以匹配不同的Markdown标记
	patterns := []string{
		"(?s)```(.*?)```",        // 代码块
		"`([^`]+)`",              // 行内代码
		`(?m)#+\s*(.*?)$`,        // 标题
		`(?m)^\s*[-*+]\s+(.*?)$`, // 无序列表项
		`\[(.*?)\]\((.*?)\)`,     // 链接
		`(?m)^>\s+(.*?)$`,        // 引用
	}

	cleanedData := data
	for _, pattern := range patterns {
		re := regexp.MustCompile(pattern)
		cleanedData = re.ReplaceAllFunc(cleanedData, func(match []byte) []byte {
			content := re.FindSubmatch(match)
			if len(content) > 1 {
				return content[1]
			}
			return match
		})
	}

	// 去除所有换行符
	cleanedData = regexp.MustCompile(`\s+`).ReplaceAll(cleanedData, []byte(" "))
	return cleanedData
}

func onHttpResponseBody(ctx wrapper.HttpContext, config PluginConfig, body []byte, log wrapper.Log) types.Action {
	log.Info("onHttpResponseBody start")
	defer log.Info("onHttpResponseBody end")

	keyI := ctx.GetContext(CacheKeyContextKey)
	if keyI == nil {
		return types.ActionContinue
	}

	var rawResponse Response
	err := json.Unmarshal(body, &rawResponse)
	if err != nil {
		log.Infof("[onHttpResponseBody] body to json err: %s", err.Error())
		return types.ActionContinue
	}

	var question string
	var answer string
	var output OutPutFormat
	if rawResponse.Choices[0].Message.Content != "" {
		cleanedBody := cleanMarkdown([]byte(rawResponse.Choices[0].Message.Content))
		err := json.Unmarshal(cleanedBody, &output)
		if err == nil {
			log.Infof("[onHttpResponseBody] question: ", output.Question)
			log.Infof("[onHttpResponseBody] answer: ", output.Answer)

			question = output.Question
			answer = output.Answer

		} else {
			question = keyI.(string)
			answer = rawResponse.Choices[0].Message.Content
		}

		//text to vector
		requestEmbedding := dashscope.Request{
			Model: "text-embedding-v2",
			Input: dashscope.Input{
				Texts: []string{question, answer},
			},
			Parameter: dashscope.Parameter{
				TextType: "query",
			},
		}
		headers := [][2]string{{"Content-Type", "application/json"}, {"Authorization", "Bearer " + config.DashScopeInfo.APIKey}}
		reqEmbeddingSerialized, _ := json.Marshal(requestEmbedding)
		config.DashScopeClient.Post(
			"/api/v1/services/embeddings/text-embedding/text-embedding",
			headers,
			reqEmbeddingSerialized,
			func(statusCode int, responseHeaders http.Header, responseBody []byte) {
				var responseEmbedding dashscope.Response
				_ = json.Unmarshal(responseBody, &responseEmbedding)
				vector := responseEmbedding.Output.Embeddings[0].Embedding
				sVector := FloatSliceToString(vector)

				fields := make(map[string]interface{})
				fields["VECTOR"] = sVector
				fields["question"] = question
				fields["answer"] = answer

				err := config.redisClient.TvsHSet(config.RedisInfo.IndexName, question, tair.TvsHSetArgs{}.New().Fields(fields), nil)
				if err != nil {
					log.Infof("[onHttpResponseBody] TvsHSet err: %s", err.Error())
				}

				err = config.redisClient.Set("lastquestion", question, nil)
				if err != nil {
					log.Infof("[onHttpResponseBody] Set lastquestion err: %s", err.Error())
				}

				err = config.redisClient.Set("lastanswer", answer, nil)
				if err != nil {
					log.Infof("[onHttpResponseBody] Set lastanswer err: %s", err.Error())
				}

				var assistantMessage Message
				assistantMessage.Role = "assistant"
				assistantMessage.Content = answer
				rawResponse.Choices[0].Message = assistantMessage

				//replace old message and resume request qwen
				newbody, err := json.Marshal(rawResponse)
				if err != nil {
					proxywasm.ResumeHttpResponse()
					return
				} else {
					log.Infof("[onHttpResponseBody] newResponseBody: ", string(newbody))
					proxywasm.ReplaceHttpResponseBody(newbody)

					log.Info("[onHttpResponseBody] response替换成功")
					proxywasm.ResumeHttpResponse()
				}
			})
	} else {
		return types.ActionContinue
	}

	return types.ActionPause
}

/*func onHttpResponseBody(ctx wrapper.HttpContext, config PluginConfig, chunk []byte, isLastChunk bool, log wrapper.Log) []byte {
	if ctx.GetContext(ToolCallsContextKey) != nil {
		// we should not cache tool call result
		return chunk
	}
	keyI := ctx.GetContext(CacheKeyContextKey)
	if keyI == nil {
		return chunk
	}
	if !isLastChunk {
		stream := ctx.GetContext(StreamContextKey)
		if stream == nil {
			tempContentI := ctx.GetContext(CacheContentContextKey)
			if tempContentI == nil {
				ctx.SetContext(CacheContentContextKey, chunk)
				return chunk
			}
			tempContent := tempContentI.([]byte)
			tempContent = append(tempContent, chunk...)
			ctx.SetContext(CacheContentContextKey, tempContent)
		} else {
			var partialMessage []byte
			partialMessageI := ctx.GetContext(PartialMessageContextKey)
			if partialMessageI != nil {
				partialMessage = append(partialMessageI.([]byte), chunk...)
			} else {
				partialMessage = chunk
			}
			messages := strings.Split(string(partialMessage), "\n\n")
			for i, msg := range messages {
				if i < len(messages)-1 {
					// process complete message
					processSSEMessage(ctx, config, msg, log)
				}
			}
			if !strings.HasSuffix(string(partialMessage), "\n\n") {
				ctx.SetContext(PartialMessageContextKey, []byte(messages[len(messages)-1]))
			} else {
				ctx.SetContext(PartialMessageContextKey, nil)
			}
		}
		return chunk
	}
	// last chunk
	//key := keyI.(string)
	stream := ctx.GetContext(StreamContextKey)
	var value string
	if stream == nil {
		var body []byte
		tempContentI := ctx.GetContext(CacheContentContextKey)
		if tempContentI != nil {
			body = append(tempContentI.([]byte), chunk...)
		} else {
			body = chunk
		}
		bodyJson := gjson.ParseBytes(body)

		value = TrimQuote(bodyJson.Get(config.CacheValueFrom.ResponseBody).Raw)
		if value == "" {
			log.Warnf("parse value from response body failded, body:%s", body)
			return chunk
		}
	} else {
		if len(chunk) > 0 {
			var lastMessage []byte
			partialMessageI := ctx.GetContext(PartialMessageContextKey)
			if partialMessageI != nil {
				lastMessage = append(partialMessageI.([]byte), chunk...)
			} else {
				lastMessage = chunk
			}
			if !strings.HasSuffix(string(lastMessage), "\n\n") {
				log.Warnf("invalid lastMessage:%s", lastMessage)
				return chunk
			}
			// remove the last \n\n
			lastMessage = lastMessage[:len(lastMessage)-2]
			value = processSSEMessage(ctx, config, string(lastMessage), log)
		} else {
			tempContentI := ctx.GetContext(CacheContentContextKey)
			if tempContentI == nil {
				return chunk
			}
			value = tempContentI.(string)
		}
	}

	var output OutPutFormat
	if value != "" {
		err := json.Unmarshal([]byte(value), &output)
		if err == nil {
			//text to vector
			requestEmbedding := dashscope.Request{
				Model: "text-embedding-v2",
				Input: dashscope.Input{
					Texts: []string{output.Question, output.Answer},
				},
				Parameter: dashscope.Parameter{
					TextType: "query",
				},
			}
			headers := [][2]string{{"Content-Type", "application/json"}, {"Authorization", "Bearer " + config.DashScopeInfo.APIKey}}
			reqEmbeddingSerialized, _ := json.Marshal(requestEmbedding)
			config.DashScopeClient.Post(
				"/api/v1/services/embeddings/text-embedding/text-embedding",
				headers,
				reqEmbeddingSerialized,
				func(statusCode int, responseHeaders http.Header, responseBody []byte) {
					var responseEmbedding dashscope.Response
					_ = json.Unmarshal(responseBody, &responseEmbedding)
					vector := responseEmbedding.Output.Embeddings[0].Embedding
					sVector := FloatSliceToString(vector)

					fields := make(map[string]interface{})
					fields["VECTOR"] = sVector
					fields["question"] = output.Question
					fields["answer"] = output.Answer

					config.redisClient.TvsHSet(config.RedisInfo.IndexName, output.Question, tair.TvsHSetArgs{}.New().Fields(fields), nil)
					proxywasm.ResumeHttpResponse()
				})
		}
	}

	return chunk
}
*/
